/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact, CompilerSettings } from 'ethereum-types';

import * as BalanceChecker from '../generated-artifacts/BalanceChecker.json';
import * as ERC20BridgeSampler from '../generated-artifacts/ERC20BridgeSampler.json';
import * as FakeTaker from '../generated-artifacts/FakeTaker.json';
import * as UniswapV3MultiQuoter from '../generated-artifacts/UniswapV3MultiQuoter.json';

const fixArtifact = (artifact: any): ContractArtifact => {
    const fixedArtifact = {
        ...artifact,
        compiler: {
            ...artifact.compiler,
            settings: {
                evmVersion: 'constantinople',
                optimizer: { enabled: true, runs: 200 },
                outputSelection: {
                    "*": {
                        "*": [
                            "abi",
                            "devdoc",
                            "evm.bytecode.object",
                            "evm.bytecode.sourceMap",
                            "evm.deployedBytecode.object",
                            "evm.deployedBytecode.sourceMap"
                        ]
                    }
                }
            } as CompilerSettings
        },
        chains: artifact.chains || {},
        sources: artifact.sources || {},
        sourceCodes: artifact.sourceCodes || {}
    };
    return fixedArtifact as ContractArtifact;
};

export const artifacts = {
    ERC20BridgeSampler: fixArtifact(ERC20BridgeSampler),
    BalanceChecker: fixArtifact(BalanceChecker),
    FakeTaker: fixArtifact(FakeTaker),
    UniswapV3MultiQuoter: fixArtifact(UniswapV3MultiQuoter),
};
